name: Build compact executables (Nuitka + UPX)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.10']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # ---------------- Linux ----------------
      - name: Install build tools (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y build-essential pkg-config python3-dev upx-ucl

      - name: Install Python deps (Linux)
        if: runner.os == 'Linux'
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install nuitka netCDF4 numpy reportlab
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build (Linux)
        if: runner.os == 'Linux'
        run: |
          ENTRY=validate_netcdf_total.py
          OUTDIR=dist
          rm -rf "$OUTDIR" build || true
          mkdir -p "$OUTDIR"
          INCLUDE_JSON="--include-data-file=cf_radial_metadata_Final.json=cf_radial_metadata_Final.json"
          python -m nuitka --onefile --lto=yes --remove-output \
            --output-dir="$OUTDIR" $INCLUDE_JSON \
            --include-package=netCDF4 \
            --include-package=numpy \
            --include-package=reportlab \
            "$ENTRY"
          ls -lah "$OUTDIR"

      # ---------------- Windows ----------------
      - name: Install build tools (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install upx -y

      - name: Pre-install depends.exe (Windows)
        if: runner.os == 'Windows'
        run: |
          $url = "https://dependencywalker.com/depends22_x64.zip"
          $zip = "$env:TEMP\depends.zip"
          $dest = "$env:LOCALAPPDATA\Nuitka\Nuitka\Cache\downloads\depends\x86_64"
          New-Item -ItemType Directory -Force -Path $dest | Out-Null
          Invoke-WebRequest -Uri $url -OutFile $zip
          Expand-Archive -Path $zip -DestinationPath $dest -Force

      - name: Install Python deps (Windows)
        if: runner.os == 'Windows'
        run: |
          python -m ensurepip --upgrade
          python -m pip install --upgrade pip setuptools wheel
          pip install nuitka netCDF4 numpy reportlab
          if (Test-Path requirements.txt) { pip install -r requirements.txt }

      - name: Build (Windows)
        if: runner.os == 'Windows'
        run: |
          $ENTRY="validate_netcdf_total.py"
          $OUTDIR="dist"
          if (Test-Path $OUTDIR) { Remove-Item $OUTDIR -Recurse -Force }
          New-Item -ItemType Directory -Path $OUTDIR | Out-Null
          $INCLUDE_JSON="--include-data-file=cf_radial_metadata_Final.json=cf_radial_metadata_Final.json"
          python -m nuitka --onefile --remove-output `
            --output-dir=$OUTDIR $INCLUDE_JSON `
            --include-package=netCDF4 `
            --include-package=numpy `
            --include-package=reportlab `
            $ENTRY
          Get-ChildItem $OUTDIR

      # ---------------- UPX compress (both OS) ----------------
      - name: Compress binary with UPX
        run: |
          if [ -d dist ]; then
            BIN=$(ls dist | head -n1)
            echo "Compressing $BIN"
            if command -v upx >/dev/null 2>&1; then
              upx --best --ultra-brute "dist/$BIN" || echo "UPX failed"
            fi
            ls -lh dist/
          fi
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: dist/*
