name: Build compact executables (Nuitka + UPX)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.10']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system build tools (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y build-essential pkg-config python3-dev upx-ucl

      - name: Install system build tools (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install upx -y
        shell: pwsh

      - name: Install Python build deps
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install nuitka
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt || true; fi
        shell: bash

      - name: Build with Nuitka
        run: |
          ENTRY=validate_netcdf_total.py
          OUTDIR=dist
          rm -rf "$OUTDIR" build || true
          mkdir -p "$OUTDIR"

          INCLUDE_JSON="--include-data-file=cf_radial_metadata_Final.json=cf_radial_metadata_Final.json"

          python -m nuitka --onefile --follow-imports --lto=yes --remove-output --output-dir="$OUTDIR" $INCLUDE_JSON "$ENTRY"

          ls -lah "$OUTDIR" || true
        shell: bash
        env:
          NUITKA_DOWNLOADS: "1"

 
      - name: Compress with UPX
        run: |
          if [ -d dist ]; then
            BIN=$(ls dist | head -n1)
            echo "Compressing: $BIN"
            if command -v upx >/dev/null 2>&1; then
              upx --best --ultra-brute "dist/$BIN" || echo "UPX compression failed"
            fi
            ls -lh dist/
          fi
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: dist/*


